#!/usr/bin/env python3
# Copyright 2026 Sasaki
# All rights reserved.
#
# Software License Agreement (BSD 2-Clause Simplified License)
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#  * Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

"""Fail-closed guard for the generated competitive claim README marker.

The guard is deliberately a publication boundary.  In the current NOT_READY
state it permits only an empty marker.  In a future READY state it reopens the
sealed publication spec/root, invokes the Phase 1 publisher into a new
temporary output, and compares the generated bytes and receipt identities with
both the README marker and the sealed root.  It never runs a scorer, opens GT,
uses the network, or edits README.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import stat
import sys
import tempfile
from typing import Any, Mapping

_SOURCE_ROOT = Path(__file__).resolve().parent.parent
if (
        (_SOURCE_ROOT / 'lidarslam_benchmark_tools' / '__init__.py').is_file()
        and (_SOURCE_ROOT / 'scripts' / 'benchmark_phase_contract.py').is_file()
        and str(_SOURCE_ROOT) not in sys.path):
    sys.path.insert(0, str(_SOURCE_ROOT))

try:
    from lidarslam_benchmark_tools import package_root
    from lidarslam_benchmark_tools.publish_competitive_claim import (
        PublicationError, publish)
except ModuleNotFoundError:  # pragma: no cover - direct checkout fallback
    from lidarslam_benchmark_tools import package_root  # type: ignore[no-redef]
    from lidarslam_benchmark_tools.publish_competitive_claim import (  # type: ignore[no-redef]
        PublicationError, publish)


ROOT = package_root()
SCHEMA_NAME = 'competitive_claim_readme_publication_v1.schema.json'
DEFAULT_CONFIG = ROOT / (
    'configs/slam_benchmark_profiles/'
    'competitive_claim_readme_publication_v1.json')
LEGACY_ALLOWLIST_SHA256 = (
    '51886466f415f69562a48276c6356aa28ee6fbb84be57d615ecbe197faafdc5e')


class ReadmeClaimGuardError(ValueError):
    """A README publication contract violation."""


def _canonical(value: Any) -> bytes:
    try:
        encoded = json.dumps(
            value, sort_keys=True, separators=(',', ':'), ensure_ascii=True,
            allow_nan=False)
    except (TypeError, ValueError) as exc:
        raise ReadmeClaimGuardError('configuration is not canonical JSON') from exc
    return encoded.encode('utf-8')


def _sha_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _strict_json(data: bytes, label: str) -> Any:
    def object_pairs(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        result: dict[str, Any] = {}
        for key, value in pairs:
            if key in result:
                raise ReadmeClaimGuardError(f'{label} contains duplicate JSON keys')
            result[key] = value
        return result

    try:
        return json.loads(data.decode('utf-8'), object_pairs_hook=object_pairs)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ReadmeClaimGuardError(f'{label} must be one UTF-8 JSON document') from exc


def _read_nofollow(path: Path, label: str) -> bytes:
    if path.is_symlink() or not path.exists():
        raise ReadmeClaimGuardError(f'{label} is missing or symlinked')
    flags = getattr(os, 'O_NOFOLLOW', 0) | os.O_RDONLY
    try:
        fd = os.open(path, flags)
    except OSError as exc:
        raise ReadmeClaimGuardError(f'{label} cannot be opened safely') from exc
    try:
        before = os.fstat(fd)
        if not stat.S_ISREG(before.st_mode) or before.st_nlink != 1:
            raise ReadmeClaimGuardError(f'{label} must be a single-link regular file')
        with os.fdopen(fd, 'rb', closefd=True) as stream:
            fd = -1
            data = stream.read()
            after = os.fstat(stream.fileno())
        if (after.st_dev != before.st_dev or after.st_ino != before.st_ino or
                after.st_nlink != 1 or after.st_size != before.st_size):
            raise ReadmeClaimGuardError(f'{label} changed during read')
        return data
    finally:
        if fd >= 0:
            os.close(fd)


def _relative(value: Any, label: str) -> str:
    if not isinstance(value, str) or not value or '\\' in value or '\x00' in value:
        raise ReadmeClaimGuardError(f'{label} must be normalized relative text')
    path = Path(value)
    if path.is_absolute() or any(part in {'', '.', '..'} for part in path.parts):
        raise ReadmeClaimGuardError(f'{label} must be normalized relative text')
    if path.as_posix() != value:
        raise ReadmeClaimGuardError(f'{label} must be normalized relative text')
    return value


def _resolve(root: Path, value: Any, label: str, *, directory: bool = False) -> Path:
    relative = _relative(value, label)
    current = root
    for component in Path(relative).parts:
        current = current / component
        try:
            info = current.lstat()
        except OSError as exc:
            raise ReadmeClaimGuardError(f'{label} is missing') from exc
        if stat.S_ISLNK(info.st_mode):
            raise ReadmeClaimGuardError(f'{label} contains a symlink')
    resolved = current.resolve(strict=True)
    try:
        resolved.relative_to(root.resolve(strict=True))
    except ValueError as exc:
        raise ReadmeClaimGuardError(f'{label} escapes repository root') from exc
    if directory:
        if not resolved.is_dir():
            raise ReadmeClaimGuardError(f'{label} must be a directory')
    elif not resolved.is_file():
        raise ReadmeClaimGuardError(f'{label} must be a regular file')
    return resolved


def _load_config(config_path: Path, repo_root: Path) -> dict[str, Any]:
    try:
        config_relative = config_path.absolute().relative_to(repo_root.absolute())
    except ValueError as exc:
        raise ReadmeClaimGuardError(
            'README guard config is outside repository root') from exc
    config_path = _resolve(repo_root, config_relative.as_posix(), 'README guard config')
    config_bytes = _read_nofollow(config_path, 'README guard config')
    config = _strict_json(config_bytes, 'README guard config')
    if not isinstance(config, Mapping):
        raise ReadmeClaimGuardError('README guard config must be a mapping')
    schema_path = config_path.parent / SCHEMA_NAME
    schema = _strict_json(_read_nofollow(schema_path, 'README guard schema'),
                          'README guard schema')
    try:
        import jsonschema
        errors = sorted(
            jsonschema.Draft7Validator(schema).iter_errors(config),
            key=lambda error: list(error.path))
    except (ImportError, TypeError, ValueError) as exc:
        raise ReadmeClaimGuardError(f'README guard schema unavailable: {exc}') from exc
    if errors:
        raise ReadmeClaimGuardError('README guard schema error: ' + errors[0].message)
    payload = {key: value for key, value in config.items() if key != 'config_sha256'}
    if config['config_sha256'] != _sha_bytes(_canonical(payload)):
        raise ReadmeClaimGuardError('README guard config self-hash mismatch')
    if config['repository_root'] != '.':
        raise ReadmeClaimGuardError('README guard repository_root must be "."')
    if config['legacy_allowlist_revision'] != 1:
        raise ReadmeClaimGuardError('unsupported legacy allowlist revision')
    if _sha_bytes(_canonical(config['legacy_allowlist'])) != LEGACY_ALLOWLIST_SHA256:
        raise ReadmeClaimGuardError(
            'README legacy allowlist changed; a versioned guard migration is required')
    if not repo_root.is_dir() or repo_root.is_symlink():
        raise ReadmeClaimGuardError('repository root is unsafe')
    return dict(config)


def _marker_body(text: str, config: Mapping[str, Any]) -> tuple[str, list[str]]:
    markers = config.get('markers')
    if not isinstance(markers, Mapping):
        raise ReadmeClaimGuardError('README markers are missing')
    begin = markers.get('begin')
    end = markers.get('end')
    if not isinstance(begin, str) or not isinstance(end, str) or begin == end:
        raise ReadmeClaimGuardError('README markers are malformed')
    if text.count(begin) != 1 or text.count(end) != 1:
        raise ReadmeClaimGuardError('README must contain exactly one marker pair')
    lines = text.splitlines(keepends=True)
    begin_rows = [index for index, line in enumerate(lines) if line.rstrip('\r\n') == begin]
    end_rows = [index for index, line in enumerate(lines) if line.rstrip('\r\n') == end]
    if len(begin_rows) != 1 or len(end_rows) != 1 or begin_rows[0] >= end_rows[0]:
        raise ReadmeClaimGuardError('README marker order or nesting is invalid')
    body = ''.join(lines[begin_rows[0] + 1:end_rows[0]])
    if begin in body or end in body:
        raise ReadmeClaimGuardError('README marker pair is nested')
    return body.replace('\r\n', '\n').replace('\r', '\n'), lines


def _paragraphs(lines: list[str]) -> list[dict[str, Any]]:
    paragraphs: list[dict[str, Any]] = []
    heading = ''
    start: int | None = None
    for row, line in enumerate(lines + [''], start=1):
        if line.startswith('#'):
            heading = line.rstrip('\r\n')
        if line.strip() and start is None:
            start = row
        if not line.strip() and start is not None:
            end = row - 1
            text = '\n'.join(item.rstrip('\r\n') for item in lines[start - 1:end]).strip()
            paragraphs.append({
                'heading': heading,
                'line_start': start,
                'line_end': end,
                'text': text,
                'sha256': _sha_bytes(text.encode('utf-8')),
            })
            start = None
    return paragraphs


def _check_legacy_allowlist(config: Mapping[str, Any], lines: list[str]) -> None:
    paragraphs = _paragraphs(lines)
    markers = config.get('markers')
    if not isinstance(markers, Mapping):
        raise ReadmeClaimGuardError('README markers are missing')
    begin = markers.get('begin')
    end = markers.get('end')
    begin_rows = [index + 1 for index, line in enumerate(lines)
                  if line.rstrip('\r\n') == begin]
    end_rows = [index + 1 for index, line in enumerate(lines)
                if line.rstrip('\r\n') == end]
    if len(begin_rows) != 1 or len(end_rows) != 1:
        raise ReadmeClaimGuardError('README marker rows are malformed')
    marker_start, marker_end = begin_rows[0], end_rows[0]
    allowlist = config.get('legacy_allowlist')
    patterns = config.get('forbidden_patterns')
    if not isinstance(allowlist, list) or not isinstance(patterns, list):
        raise ReadmeClaimGuardError('README guard allowlist/patterns are malformed')
    allowed: set[tuple[str, str]] = set()
    seen_ids: set[str] = set()
    for entry in allowlist:
        if not isinstance(entry, Mapping):
            raise ReadmeClaimGuardError('README legacy allowlist entry is malformed')
        legacy_id = entry.get('legacy_id')
        if not isinstance(legacy_id, str) or legacy_id in seen_ids:
            raise ReadmeClaimGuardError('README legacy allowlist IDs must be unique')
        seen_ids.add(legacy_id)
        key = (entry['heading'], entry['sha256'])
        matches = [item for item in paragraphs
                   if (item['heading'], item['sha256']) == key]
        if len(matches) != 1:
            raise ReadmeClaimGuardError(
                'README legacy allowlist entry must match exactly one paragraph')
        allowed.add(key)
    compiled = []
    try:
        compiled = [re.compile(pattern, re.IGNORECASE) for pattern in patterns]
    except re.error as exc:
        raise ReadmeClaimGuardError(f'README forbidden pattern is invalid: {exc}') from exc
    for paragraph in paragraphs:
        if (paragraph['line_start'] <= marker_end and
                paragraph['line_end'] >= marker_start):
            continue
        if any(pattern.search(paragraph['text']) for pattern in compiled):
            key = (paragraph['heading'], paragraph['sha256'])
            if key not in allowed:
                raise ReadmeClaimGuardError(
                    'README contains a new comprehensive/universal claim outside marker')


def _normalise_newlines(value: bytes) -> bytes:
    return value.replace(b'\r\n', b'\n').replace(b'\r', b'\n')


def _verify_ready(config: Mapping[str, Any], repo_root: Path, readme_body: str) -> dict[str, Any]:
    if not readme_body:
        raise ReadmeClaimGuardError('READY README marker must contain generated Markdown')
    spec_path = _resolve(repo_root, config['publication_spec'], 'publication_spec')
    sealed_root = _resolve(repo_root, config['sealed_root'], 'sealed_root', directory=True)
    sealed_claim_path = _resolve(sealed_root, 'claim.md', 'sealed claim')
    sealed_receipt_path = _resolve(sealed_root, 'publication_receipt.json',
                                   'sealed publication receipt')
    sealed_claim = _read_nofollow(sealed_claim_path, 'sealed claim')
    sealed_receipt = _strict_json(
        _read_nofollow(sealed_receipt_path, 'sealed publication receipt'),
        'sealed publication receipt')
    if (not isinstance(sealed_receipt, Mapping) or
            sealed_receipt.get('status') != 'PASS' or
            sealed_receipt.get('claim_eligible') is not True):
        raise ReadmeClaimGuardError('sealed publication receipt is not PASS/claim eligible')
    receipt_sha = sealed_receipt.get('receipt_sha256')
    rendered_sha = sealed_receipt.get('rendered_markdown_sha256')
    if (not isinstance(receipt_sha, str) or len(receipt_sha) != 64 or
            not isinstance(rendered_sha, str) or len(rendered_sha) != 64):
        raise ReadmeClaimGuardError('sealed publication receipt hashes are missing')
    with tempfile.TemporaryDirectory(prefix='.competitive-claim-readme-') as temporary:
        output_root = Path(temporary) / 'published'
        try:
            published = publish(spec_path, output_root)
        except (OSError, PublicationError, TypeError, ValueError) as exc:
            raise ReadmeClaimGuardError(f'Phase 1 publisher failed: {exc}') from exc
        if published.get('status') != 'PASS' or published.get('claim_eligible') is not True:
            raise ReadmeClaimGuardError('Phase 1 publisher did not return PASS/claim eligible')
        generated_claim = _read_nofollow(output_root / 'claim.md', 'generated claim')
        generated_receipt = _strict_json(
            _read_nofollow(output_root / 'publication_receipt.json', 'generated receipt'),
            'generated receipt')
        if (not isinstance(generated_receipt, Mapping) or
                generated_receipt.get('receipt_sha256') != receipt_sha or
                generated_receipt.get('rendered_markdown_sha256') != rendered_sha or
                published.get('rendered_markdown_sha256') != rendered_sha or
                published.get('receipt_sha256') != receipt_sha):
            raise ReadmeClaimGuardError(
                'generated publication receipt does not match sealed receipt')
        if (_sha_bytes(sealed_claim) != rendered_sha or
                _sha_bytes(generated_claim) != rendered_sha):
            raise ReadmeClaimGuardError('sealed/generated claim Markdown hash mismatch')
        if (_normalise_newlines(generated_claim) !=
                _normalise_newlines(readme_body.encode('utf-8'))):
            raise ReadmeClaimGuardError('README marker does not equal generated claim Markdown')
        return {
            'status': 'PASS', 'claim_eligible': True,
            'receipt_sha256': receipt_sha,
            'rendered_markdown_sha256': rendered_sha,
        }


def verify(
        readme_path: Path, config_path: Path, *,
        repo_root: Path | None = None) -> dict[str, Any]:
    """Validate the README marker and its publication boundary."""
    root = (repo_root or ROOT).resolve(strict=True)
    config = _load_config(config_path.absolute(), root)
    if readme_path.is_absolute():
        try:
            readme_relative = readme_path.absolute().relative_to(root.absolute())
        except ValueError as exc:
            raise ReadmeClaimGuardError('readme path is outside repository root') from exc
        readme = _resolve(root, readme_relative.as_posix(), 'readme')
    else:
        readme = _resolve(root, config['readme_path'], 'readme')
    text = _read_nofollow(readme, 'README').decode('utf-8')
    body, lines = _marker_body(text, config)
    _check_legacy_allowlist(config, lines)
    if config['status'] == 'NOT_READY':
        placeholder = config['placeholder']
        allowed = {'', placeholder, placeholder + '\n'}
        if body not in allowed:
            raise ReadmeClaimGuardError(
                'NOT_READY README marker must be empty or the configured placeholder')
        return {'status': 'PASS', 'claim_eligible': False, 'publication_status': 'NOT_READY'}
    return _verify_ready(config, root, body)


def main(argv: list[str] | None = None) -> int:
    """Run the README publication guard CLI."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--repo-root', type=Path, default=ROOT)
    parser.add_argument('--readme', type=Path)
    parser.add_argument('--config', type=Path, default=DEFAULT_CONFIG)
    args = parser.parse_args(argv)
    try:
        result = verify(
            args.readme.absolute() if args.readme is not None
            else _resolve(args.repo_root.resolve(strict=True), 'README.md', 'readme'),
            args.config,
            repo_root=args.repo_root,
        )
    except (OSError, ReadmeClaimGuardError, PublicationError, TypeError, ValueError) as exc:
        print(json.dumps({
            'status': 'FAIL_CLOSED', 'claim_eligible': False, 'error': str(exc),
        }, sort_keys=True), file=sys.stderr)
        return 2
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
